var result;
result='3'+2;
console.log(result);
result='3'+ true;
console.log(result);
result='3'+ undefined;
console.log(result);
result='3'+null;
console.log(result);
console.log("For above all examples,It used implicite conversion of number 3 into string, so addition not done,it concatinate string and number");
console.log("Implicite boolean conversion to number");
result=4-true;
console.log(result);
result= 4+ true;
console.log(result);
result=4-false;
console.log(result);
console.log("for above caess there is implicite conversion of boolean values true and false takes 1 and 0 values respectivelly. so that it shows addition and substration with number");
result='4'-'2';
console.log(result);
result='4'-2;
console.log(result);
result='4'*2;
console.log(result);
result='4'/2;
console.log(result);
console.log("for above cases-when number is in '' it is considered as string but if thar string number comes with -,/,* it implicitely converted into number");
result=4 + undefined;
console.log(result);
result=4 - undefined;
console.log(result);
result=true + undefined;
console.log(result);
result=null + undefined;
console.log(result);
